apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: queen
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - queen.dev.insee.io
  rules:
    - host: queen.dev.insee.io
      http:
        paths:
          - path: /
            backend:
              serviceName: queen
              servicePort: http
