apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "queen.ui.fullname" . }}
  labels:
    {{- include "queen.ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      {{- include "queen.ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "queen.ui.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "queen.ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.ui.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.ui.securityContext | nindent 12 }}
          image: "{{ .Values.ui.image.name }}:{{ .Values.ui.image.version }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          env:
          {{- if .Values.ingress.enabled }}
            {{- if .Values.ingress.tls }}
            - name: API_URL_CI
              value: {{ printf "https://%s/%s" .Values.ingress.hostname "api/" | quote }}
              {{- else }}
            - name: API_URL_CI
              value: {{ printf "http://%s/%s" .Values.ingress.hostname "api/" | quote }}
            {{- end}}
          {{- end}}
            {{- range .Values.ui.env }}
          - name: {{ .name }}
            value: {{ .value }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
