name: Queen UI Release Candidate (RC) release publication

on:
  push:
    branches:
      - 'develop'
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
      - name: Get current version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'package.json'
          prop_path: 'version'
      - run: echo ${{steps.version.outputs.prop}}
      - name: Release snapshot
        id: release-snapshot
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.version.outputs.prop}}-rc
          release_name: ${{steps.version.outputs.prop}}-rc
          draft: false
          prerelease: false